ALTER TABLE EJERCICIO ALTER COLUMN "FINALIZADO" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE USER ALTER COLUMN "ENABLED" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE MONEDA ALTER COLUMN "IS_DEFAULT" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE MONEDA ALTER COLUMN "AJUSTABLE" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE CUENTA SET ACTIVA = FALSE WHERE ACTIVA IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "ACTIVA" BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE CUENTA SET INDIVIDUAL = FALSE WHERE INDIVIDUAL IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "INDIVIDUAL" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE CUENTA SET RESULTADO = FALSE WHERE RESULTADO IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "RESULTADO" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE CUENTA SET AJUSTABLE = FALSE WHERE AJUSTABLE IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "AJUSTABLE" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE CUENTA SET BALANCEA_RESULTADOS = FALSE WHERE BALANCEA_RESULTADOS IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "BALANCEA_RESULTADOS" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE CUENTA SET BALANCEA_AJUSTABLES = FALSE WHERE BALANCEA_AJUSTABLES IS NULL;
ALTER TABLE CUENTA ALTER COLUMN "BALANCEA_AJUSTABLES" BOOLEAN NOT NULL DEFAULT FALSE;