MERGE INTO IMPUTACION(ID, ORDEN) KEY(ID) SELECT ID, ROW_NUMBER() OVER (PARTITION BY ASIENTO_ID ORDER BY ID) FROM IMPUTACION;

ALTER TABLE IMPUTACION ALTER COLUMN ORDEN SMALLINT NOT NULL SELECTIVITY 1 CHECK ("ORDEN" >= 1);